#Use an official Node runtime as a parent image
FROM node:18.15.0

#Set the working directory in the container
WORKDIR /usr/src/app

#Copy package.json and package-lock.json to the working directory
COPY package*.json ./

#Install app dependencies
RUN npm install

#Bundle app source
COPY . .

#Make port 8080 available to the world outside this container
EXPOSE 8080

#Define environment variable
ENV NODE_ENV production

#Rebuild bcrypt
RUN npm rebuild bcrypt --build-from-source

#Run app.js when the container launches
CMD ["node", "index.js"]
